  <div class="row">
      
      <div class="col s12 m12">
        <div class="card-panel blue-grey lighten-5">
          <div class="row">
            <div class="col s12 m12 l12">
              <table class="highlight centered">
                <thead>
                  <tr>
                    <th>Fullname</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Address</th>
                    <th>Delete</th>
                  </tr>
                </thead>
                <tbody>
                  <?php foreach ($users as $key => $userRow) { ?>
                  <tr>
                    <td><?php echo $userRow["fullname"]; ?></td>
                    <td><?php echo $userRow["username"]; ?></td>
                    <td><?php echo $userRow["email"]; ?></td>
                    <td><?php echo $userRow["phone"]; ?></td>
                    <td><?php echo $userRow["address"]; ?></td>
                    <td><a href="#!" class="delete-btn"><i class="material-icons">delete</i></a></td>
                  </tr>
                  <?php } ?>

                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      
  </div>