  <div class="row">
      
      <div class="col s12 m12">
        <div class="card-panel blue-grey lighten-5">
          <div class="row">
            <div class="col s12 m12 l12">
              <table class="highlight centered">
                <thead>
                  <tr>
                    <th>Fullname</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Address</th>
                    <th>Delete</th>
                  </tr>
                </thead>
                <tbody>
                  <?php foreach ($users as $key => $userRow) { ?>
                  <tr id="user<?php echo $userRow['id']; ?>">
                    <td><?php echo $userRow["fullname"]; ?></td>
                    <td><?php echo $userRow["username"]; ?></td>
                    <td><?php echo $userRow["email"]; ?></td>
                    <td><?php echo $userRow["phone"]; ?></td>
                    <td><?php echo $userRow["address"]; ?></td>
                    <td><a href="#!" onclick="deleteConfirm(<?php echo $userRow['id']; ?>)" class="delete-btn"><i class="material-icons">delete</i></a></td>
                  </tr>
                  <?php } ?>

                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      
  </div>



  <!-- Delete confirm Modal Structure -->
  <div id="deleteConfirm" class="modal confirm-modal">
    <div class="modal-content">
      <h4 class="center-align">Delete User</h4>
      <p class="center-align">Are you sure you want to delete this user?</p>
    </div>
    <div class="row modal-footer">
    		<div class="col s2"></div>
    		<div class="col s4"><a href="#!" class="btn-full modal-action modal-close waves-effect waves-green btn">Close</a></div>
    		<div class="col s4"><a id="deleteBtn" href="#!" class="btn-full btn waves-effect waves-green deep-orange darken-3">Delete</a></div>
    		<div class="col s2"></div>
    </div>
  </div>




  <!-- Update Modal Structure -->
  <div id="updateUser" class="modal">
    <div class="modal-content">
      <h4 class="center-align">Update User</h4>
      <div class="row">
                <form class="col s12">


                    <div class="input-field col s12">
                      <input id="fullname" type="text" class="validate">
                      <label for="fullname">Fullname</label>
                    </div>



                    <div class="input-field col s12">
                      <input id="username" type="text" class="validate">
                      <label for="username">Username</label>
                    </div>


                    <div class="input-field col s12">
                      <input id="email" type="email" class="validate">
                      <label for="email">Email</label>
                    </div>



                    <div class="input-field col s12">
                      <input id="phone" type="text" class="validate">
                      <label for="phone">Contact Number</label>
                    </div>



                    <div class="input-field col s12">
                      <input id="address" type="text" class="validate">
                      <label for="address">Address</label>
                    </div>


                  <a id="saveUser" class="waves-effect waves-light btn-large btn-full">Submit</a>

                </form>
              </div>

    </div>

  </div>