<div class="row">
      
      <div class="create-user-container col s6 m6">
        <div class="card-panel blue-grey lighten-5">
          <div class="row">
            <div class="col s12 m12 l12">




              <div class="row">
                <form class="col s12">

                  <div class="row">
                    <div class="input-field col s12">
                      <input id="fullname" type="text" class="validate">
                      <label for="fullname">Fullname</label>
                    </div>
                  </div>

                  <div class="row">
                    <div class="input-field col s12">
                      <input id="username" type="text" class="validate">
                      <label for="username">Username</label>
                    </div>
                  </div>

                  <div class="row">
                    <div class="input-field col s12">
                      <input id="email" type="email" class="validate">
                      <label for="email">Email</label>
                    </div>
                  </div>

                  <div class="row">
                    <div class="input-field col s12">
                      <input id="phone" type="text" class="validate">
                      <label for="phone">Contact Number</label>
                    </div>
                  </div>

                  <div class="row">
                    <div class="input-field col s12">
                      <input id="address" type="text" class="validate">
                      <label for="address">Address</label>
                    </div>
                  </div>

                  <a id="saveUser" class="waves-effect waves-light btn-large btn-full">Submit</a>

                </form>
              </div>






            </div>
          </div>
        </div>
      </div>
      
  </div>