<?php echo $this->doctype(); ?>

<html lang="en">
<head>

    <?php echo $this->headTitle('Code Test')->setSeparator(' - ')->setAutoEscape(
        false
    ) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <?php echo $this->headLink()->appendStylesheet($this->basePath('css/materialize.css')); ?>
    <?php echo $this->headLink()->appendStylesheet($this->basePath('css/style.css')); ?>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('js/materialize.js'); ?>"></script>
    <?php echo $this->headScript()->appendFile($this->basePath('js/script.js')); ?>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<body>
<nav>
    <div class="nav-wrapper blue-grey darken-4">
        <a href="#" class="brand-logo">CODE TEST</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="<?php echo $this->basePath('user/index'); ?>">USERS</a></li>
            <li><a href="<?php echo $this->basePath('user/add'); ?>">ADD</a></li>
        </ul>
    </div>
</nav>


<div class="container">
    <?php echo $this->content; ?>
</div>
<input type="hidden" id="baseURL" value="<?php echo $this->serverUrl().$this->basePath(); ?>" />
</body>
</html>