<?php echo $this->doctype(); ?>

<html lang="en">
<head>

    <?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(
        false
    ) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <?php echo $this->headLink()->appendStylesheet($this->basePath('css/bootstrap.min.css')); ?>

</head>

<body>

<div class="container">
    <header>
        <h1>ZF2 and Doctrine2 Application Ready!</h1>
    </header>
    <?php echo $this->content; ?>
</div>

</body>
</html>